### PR TITLE
(Untested) Change MAGIC Letters to FOSS Letters

### PR DESCRIPTION
**Pull request by ct-martin**
Couldn't test on my laptop so this was in the blind. In theory it should hopefully work though.

* Change letters
* Change font (NOTE: non-libre font used; talk to @nlmeminger since he chose it)
* Change backend letter mappings in accordance with new letters

### CODE REVIEW

**Comment by nlMeminger** [comment]
@schneidy or @KST123ABC can you take a look at this since you're more familiar with the code than I am?

**Comment by schneidy** [comment]
I might be able look at it in a week.

**Comment by kyputer** [comment]
Had to change the identifiers. S1 and S2 will not work because those keywords are in use w/ bootstrap. Added the new letters as models in the DB, we get a 200 when we change the color, but the colors or the text does not actually change like the last project. I wish I had time to dive deeper but I am wrapping up capstone and independent study this week. I changed the S2 to Z and S1 to S and now it at least loads :)

P.S. Font is not being found.

**Comment by kyputer** [comment]
Shouldn't have been closed. No idea how I did that.
@ct-martin I think it should work if we do not use this font with the changes made. I tried with the MAGIC assets to make sure.

**Pull request closed without merging**
